### PR TITLE
Add C# service template

### PR DESCRIPTION
**Pull request by MvnTruong**
[NEX-5111](https://altiumrd.atlassian.net/browse/NEX-5111)

Adding a bare minimum C# (ASP.NET Core) server that candidates can work from.

I've also updated the `data.json` stub for all three projects.

[NEX-5111]: https://altiumrd.atlassian.net/browse/NEX-5111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by MvnTruong** [comment]
The issue with C# is that it's strongly typed, so for any candidates who'd want to deserialize the sample data in a type-safe way, they will have to carve out a bit of time to define each class in order to do something like: `JsonSerializer.Deserialize<PartsData>(json)`. So I'm wondering if we want to level the playing field a bit for C# candidates by defining the types for them in the sample template.

Thoughts?

**Comment by RobAltium** [comment]
> The issue with C# is that it's strongly typed, so for any candidates who'd want to deserialize the sample data in a type-safe way, they will have to carve out a bit of time to define each class in order to do something like: `JsonSerializer.Deserialize<PartsData>(json)`. So I'm wondering if we want to level the playing field a bit for C# candidates by defining the types for them in the sample template.
> 
> Thoughts?

Yes, that makes sense.  Or there are tools we can point candidates at, such as https://quicktype.io/csharp.  But I would provide this on request as you suggest.

**Comment by khwong-altium** [comment]
Minor refinement:
We can `.gitignore` the `.idea` part and remove them from the branch, for a more IDE neutral setup.

**Comment by MvnTruong** [comment]
> We can `.gitignore` the `.idea` part and remove them from the branch, for a more IDE neutral setup.

@khwong-altium Yeah, that makes sense - done.

> Or there are tools we can point candidates at, such as https://quicktype.io/csharp. But I would provide this on request as you suggest.

@RobAltium Pointing them to a type generator is a good option, or they can even use ChatGPT here. So I agree, let's leave the types out for now

**Review by RobAltium — APPROVED** [review]
The C# app looks reasonable.  Please check @khwong-altium is happy with the JSON file changes.

**Comment by khwong-altium** [comment]
Yes I am good with the JSON file changes

**Review by khwong-altium — APPROVED** [review]

**Pull request merged**
